// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    console.log('admin menu');
    return $('ul.admin-menu li').on('click', function() {
      var action;
      action = $(this).prop('id');
      console.log(action);
      $.ajax({
        type: 'POST',
        url: './php/admin_menu.php',
        data: {
          action: action
        },
        async: false,
        success: function(html) {
          return $('.admin-content').html(html);
        },
        error: function() {
          return console.log('admin menu error');
        }
      });
      return $.ajax({
        type: 'POST',
        url: './php/admin/admin_data.php',
        data: {
          action: action
        },
        async: false,
        dataType: 'json',
        success: function(res) {
          var table;
          console.log(res.data);
          table = $('tbody');
          $(table).parent().attr('action', action);
          return $.each(res.data, function() {
            var row;
            row = $('<tr></tr>').attr('row-id', this.id);
            $(row).append($("<td><input type='checkbox'></td>"));
            $.each(this, function(key, value) {
              if (key !== 'id') {
                if (key === 'foto') {
                  return $(row).append($("<td><a href='#'>фото</a></td>"));
                } else {
                  return $(row).append($("<td>" + value + "</td>"));
                }
              }
            });
            return $(table).append(row);
          });
        },
        error: function(data) {
          return console.log(data.responseText);
        }
      });
    });
  });

}).call(this);
