// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var auth;
    console.log($.session.get('auth'));
    if ($.session.get('auth') === 'true') {
      $.ajax({
        type: 'POST',
        url: './admin_menu.html',
        success: function(html) {
          return $('#admin-interface').html(html);
        }
      });
    }
    auth = function() {
      return $.ajax({
        type: 'POST',
        url: './php/auth.php',
        async: false,
        dataType: 'json',
        data: {
          user: $('#input-user').val(),
          pass: $('#input-pass').val()
        },
        success: function(res) {
          console.log(res.result);
          $.session.set('auth', res.result);
          return location.reload(true);
        },
        error: function(data) {
          return console.log(data.responseText);
        }
      });
    };
    return $('#sign-in').on('click', function(e) {
      e.preventDefault();
      return auth();
    });
  });

}).call(this);
