// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    return $('#admin-delete').on('click', function(e) {
      var action, str_values;
      e.preventDefault();
      action = $('table').attr('action');
      str_values = [];
      $('input:checked').each(function() {
        return str_values.push($(this).closest('tr').attr('row-id'));
      });
      return $.ajax({
        type: 'POST',
        url: './php/edit/delete_row.php',
        dataType: 'json',
        data: {
          table: action,
          values: str_values
        },
        success: function(res) {
          console.log(res);
          return $.each(str_values, function() {
            console.log(this);
            return $("tr[row-id='" + this + "']").remove();
          });
        },
        error: function(data) {
          return console.log('err: %s', data.responseText);
        }
      });
    });
  });

}).call(this);
