// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    dictionary({
      data: {
        table: 'animal_type',
        id: 'id_animal_type',
        value: 'name'
      },
      control: '#type'
    });

    /*dictionary
      data:
        table: 'vallere'
        id: 'id_vallere'
        value: 'label'
        where:
          id_vallere_type: 1
      control: '#vallere-list'
     */
    $('input[type="file"]').on('change', function(e) {
      var file;
      console.log('image selected');
      file = e.target.files[0];
      return uploadImage(file, 'img');
    });
    return $('#add').on('click', function() {
      return $.ajax({
        type: 'POST',
        url: './php/edit/animal_insert.php',
        dataType: 'json',
        data: {
          name: $('#name').val(),
          id_type: $('#type').val(),
          comment: $('#comment').val(),
          foto: $('img').attr('src')
        },
        success: function(res) {
          console.log(res.data);
          return admin_data('animal');
        },
        error: function(data) {
          return console.log(data.responseText);
        }
      });
    });
  });

}).call(this);
