// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    return $.ajax({
      type: 'POST',
      url: './php/animals_in_vallere.php'
    }).done(function(data) {
      var objData, tmpl;
      objData = $.parseJSON(data);
      tmpl = $('.animal');
      tmpl.hide();
      return $.each(objData, function() {
        var element, list;
        element = tmpl.clone();
        list = tmpl.parent();
        element.find('.animal-name').html(this.name);
        element.appendTo(list);
        return element.fadeIn(100);
      });
    });
  });

}).call(this);
