// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    $(document).on('click', '.get-friend', function(e) {
      e.preventDefault();
      $('.alert').slideUp(200);
      $('#get-friend-form').find('#id-animal').val($(this).closest('li.animal').find('.id-animal').val());
      return $('#get-friend-form').modal('show');
    });
    $('#seach-friend').on('click', function() {
      var seach_keys;
      seach_keys = $('#seach-input').val().split(' ');
      return $('.animal-info').each(function() {
        var element, seach_text;
        element = $(this).closest('li.animal');
        if (!element.hasClass('tmpl')) {
          element.hide();
          seach_text = $(this).html();
          return $.each(seach_keys, function() {
            if (String(seach_text).indexOf(this) !== -1) {
              return element.fadeIn(300);
            }
          });
        }
      });
    });
    return $.ajax({
      type: 'POST',
      url: './php/animals_in_vallere.php'
    }).done(function(data) {
      var objData, tmpl;
      objData = $.parseJSON(data);
      tmpl = $('.animal');
      tmpl.hide();
      return $.each(objData, function() {
        var element, list;
        element = tmpl.clone();
        element.removeClass('tmpl');
        list = tmpl.parent();
        element.find('.animal-name').html(this.name);
        element.find('.animal-info').html(this.comment);
        element.find('img').prop('src', "php/foto.php?id=" + this.id_animal + "&from=animal");
        element.find('.id-animal').val(this.id_animal);
        element.appendTo(list);
        return element.fadeIn(500);
      });
    });
  });

}).call(this);
