// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    return $(document).on('focus', '.dtp', function() {
      console.log('!!!');
      $(':focus').datepicker({
        language: "ru",
        autoclose: true,
        todayHighlight: true
      });
      return $(':focus').datepicker('show');
    });
  });

}).call(this);
