// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    window.currentDate = function() {
      var d, day, month;
      d = new Date();
      month = d.getMonth() + 1;
      day = d.getDate();
      return "" + (day < 10 ? 0 : void 0) + day + "." + (month < 10 ? 0 : void 0) + month + "." + (d.getFullYear());
    };
    return $(document).on('focus', '.dtp', function() {
      var control;
      control = $(':focus').context.activeElement;
      console.log(control);
      return $(control).datepicker({
        language: "ru",
        autoclose: true,
        todayHighlight: true
      });
    });
  });


  /*
      $(':focus').datepicker('show')
   */

}).call(this);
