// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    return $.ajax({
      type: 'POST',
      url: './php/events_list.php',
      async: false,
      dataType: 'json',
      success: function(res) {
        var template;
        template = $('.event-templait');
        $.each(res.data, function() {
          var event;
          event = $(template).clone();
          $(event).find('.event-text').html(this.text);
          $(event).find('.event-date').html(this.date);
          $(template).parent().append(event);
          return $(event).show();
        });
        return console.log(res);
      },
      error: function(data) {
        return console.log(data.responseText);
      }
    });
  });

}).call(this);
