// Generated by CoffeeScript 1.8.0
(function() {
  window.dictionary = function(prop) {
    return $.ajax({
      type: 'POST',
      url: './php/dictionary_list.php',
      data: prop.data,
      dataType: 'json',
      success: function(res) {
        var select;
        select = $(prop.control);
        return $.each(res.data, function() {
          var item;
          item = $('<option></option>').val(this.value).html(this.text);
          return $(select).append(item);
        });
      },
      error: function(data) {
        return console.log(data.responseText);
      }
    });
  };

}).call(this);
