// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    return $('#add').on('click', function() {
      return $.ajax({
        type: 'POST',
        url: './php/edit/event_insert.php',
        dataType: 'json',
        data: {
          date: $('#date').val(),
          text: $('#text').val()
        },
        success: function(res) {
          return console.log(res.data);
        },
        error: function(data) {
          return console.log(data.responseText);
        }
      });
    });
  });

}).call(this);
