// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var messageData;
    messageData = {};
    $('input[type="file"]').on('change', function(e) {
      var file;
      file = e.target.files[0];
      return uploadImage(file, '#loaded-file');
    });
    $('#message-persone').on('click', function() {
      messageData.foundImage = $('#loaded-file').attr('src');
      messageData.longitude = found_map.getCenter().lng();
      messageData.latitude = found_map.getCenter().lat();
      messageData.comment = $('#found-comment').val();
      console.log(messageData);
      return $('#form-message-persone').modal('show');
    });
    return $('#geristrate-message').on('click', function() {
      messageData.firsName = $('#first-name').val();
      messageData.lastName = $('#last-name').val();
      messageData.phone = $('#contact-phone').val();
      return $.ajax({
        type: 'POST',
        url: './php/found_message.php',
        data: messageData,
        dataType: 'json',
        success: function(data) {
          return $('#form-message-persone').modal('hide');
        },
        error: function(data) {
          return console.log(data.responseText);
        }
      });
    });
  });

}).call(this);
