// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    return $('input[type="file"]').on('change', function(e) {
      var data, file;
      file = e.target.files[0];
      data = new FormData;
      data.append('file', file);
      return $.ajax({
        url: './php/upload.php',
        type: 'POST',
        data: data,
        cache: false,
        dataType: 'json',
        processData: false,
        contentType: false,
        success: function(data, textStatus, jqXHR) {
          return $('#loaded-file').prop('src', data.file);
        },
        error: function(jqXHR, textStatus, errorThrown) {
          console.log('Error !!! %s - %s', textStatus, errorThrown);
          return console.log(jqXHR.responseText);
        }
      });
    });
  });

}).call(this);
