// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var action, row;
    action = 'add';
    row = null;
    $('#item-form').on('show', function(e) {
      var values;
      if ($(e.target).attr('id') === $(this).attr('id')) {
        action = $('#item-form').attr('action');
        row = $('input:checked').closest('tr');
        values = {
          sd: {
            edit: $(row).children().eq(4).html(),
            add: currentDate()
          },
          ed: {
            edit: $(row).children().eq(5).html(),
            add: currentDate()
          },
          vallere: {
            edit: $(row).children().eq(1).attr('id-dic'),
            add: -1
          },
          animal: {
            edit: $(row).children().eq(3).attr('id-dic'),
            add: -1
          }
        };
        $('#sd').val(values.sd[action]);
        $('#ed').val(values.ed[action]);
        $('#vallere-list').val(values.vallere[action]);
        return $('#animal-list').val(values.animal[action]);
      }
    });
    dictionary({
      data: {
        table: 'animal',
        id: 'id_animal',
        value: 'name'
      },
      control: '#animal-list'
    });
    dictionary({
      data: {
        table: 'vallere',
        id: 'id_vallere',
        value: 'label'
      },
      control: '#vallere-list'
    });
    return $('#add').on('click', function() {
      var urls;
      urls = {
        add: './php/edit/hotel_insert.php',
        edit: './php/edit/hotel_update.php'
      };
      return $.ajax({
        type: 'POST',
        url: urls[action],
        dataType: 'json',
        data: {
          id: $(row).attr('row-id'),
          sd: $('#sd').val(),
          ed: $('#ed').val(),
          id_animal: $('#animal-list').val(),
          id_vallere: $('#vallere-list').val()
        },
        success: function(res) {
          console.log(res.data);
          return admin_data('hotel');
        },
        error: function(data) {
          return console.log(data.responseText);
        }
      });
    });
  });

}).call(this);
