// Generated by CoffeeScript 1.8.0
(function() {
  window.uploadImage = function(aFile, aImg) {
    var data;
    data = new FormData;
    data.append('file', aFile);
    return $.ajax({
      url: './php/upload.php',
      type: 'POST',
      data: data,
      cache: false,
      dataType: 'json',
      processData: false,
      contentType: false,
      success: function(data, textStatus, jqXHR) {
        return $(aImg).prop('src', data.file);
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.log('Error !!! %s - %s', textStatus, errorThrown);
        return console.log(jqXHR.responseText);
      }
    });
  };

}).call(this);
