// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var action, row;
    action = 'add';
    row = null;
    $('#item-form').on('show', function() {
      var values;
      action = $('#item-form').attr('action');
      row = $('input:checked').closest('tr');
      values = {
        label: {
          edit: $(row).children().eq(1).html(),
          add: ''
        },
        type: {
          edit: $(row).children().eq(2).attr('id-dic'),
          add: -1
        },
        img: {
          edit: $(row).find('a').attr('href'),
          add: ''
        }
      };
      $('#label').val(values.label[action]);
      $('#type').val(values.type[action]);
      return $('img').attr('src', values.img[action]);
    });
    dictionary({
      data: {
        table: 'vallere_type',
        id: 'id_vallere_type',
        value: 'name'
      },
      control: '#type'
    });
    $('input[type="file"]').on('change', function(e) {
      var file;
      console.log('image selected');
      file = e.target.files[0];
      return uploadImage(file, 'img');
    });
    return $('#add').on('click', function() {
      var urls;
      urls = {
        add: './php/edit/vallere_insert.php',
        edit: './php/edit/vallere_update.php'
      };
      return $.ajax({
        type: 'POST',
        url: urls[action],
        dataType: 'json',
        data: {
          id: $(row).attr('row-id'),
          label: $('#label').val(),
          id_vallere_type: $('#type').val(),
          foto: $('img').attr('src')
        },
        success: function(res) {
          console.log(res.data);
          return admin_data('vallere');
        },
        error: function(data) {
          return console.log(data.responseText);
        }
      });
    });
  });

}).call(this);
