// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    dictionary({
      data: {
        table: 'vallere_type',
        id: 'id_vallere_type',
        value: 'name'
      },
      control: '#type'
    });
    $('input[type="file"]').on('change', function(e) {
      var file;
      console.log('image selected');
      file = e.target.files[0];
      return uploadImage(file, 'img');
    });
    return $('#add').on('click', function() {
      return $.ajax({
        type: 'POST',
        url: './php/edit/vallere_insert.php',
        dataType: 'json',
        data: {
          label: $('#label').val(),
          id_vallere_type: $('#type').val(),
          foto: $('img').attr('src')
        },
        success: function(res) {
          return console.log(res.data);
        },
        error: function(data) {
          return console.log(data.responseText);
        }
      });
    });
  });

}).call(this);
